baseURL = "https://suspicious-booth-fced28.netlify.app"
languageCode = "en-us"
title = "Matt Malishev"
theme = "timer-hugo"

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

# Site Menus
[menu]
# Navbar Menus
[[menu.main]]
    name    = "About"
    url     = "about"
    weight  = 2
[[menu.main]]
    name    = "Blog"
    url     = "blog"
    weight  = 3
[[menu.main]]
    name    = "Service"
    url     = "service"
    weight  = 4
[[menu.main]]
    name    = "Gallery"
    url     = "gallery"
    weight  = 5
[[menu.main]]
    name    = "Contact"
    url     = "contact"
    weight  = 6
[[menu.main]]
    name    = "Projects"
    url     = "portfolio"
    weight  = 7

# Site Params
[params]
    home = "Home"
    logo = "images/mm.png"
    dateFormat = "6 January 2006"
    # Meta data
    description = "darwinanddavis"
    author = "Matt Malishev"
    # Google Analitycs
    googleAnalitycsID = "darwinanddavis"

    # Banner Section
    [params.banner]
        enable  = true
        bgImage = "images/header.jpeg"
        heading = "Matt Malishev"
        description = "I like my data diverse, my methods clean, my analyses reproducible, and my outputs open access."
        btn     = true
        btnText = "Check out my projects"
        btnURL  = "projects"
        [[params.banner.flipText]]
            title   = "data analysis"
        [[params.banner.flipText]]
            title   = "time series modelling"
        [[params.banner.flipText]]
            title   = "geospatial analytics"
        [[params.banner.flipText]]
            title   = "data viz"
        [[params.banner.flipText]]
            title   = "cartography"

    # Homepage About Section
    [params.about]
        enable  = true
        title   = "Bio"
        content = "I’m a computational researcher at Emory University working on diverse data analysis problems from simulation modelling of human disease risk to spatial and bioenergetic modelling of ecological systems. <br> <br> The header tabs provide a snapshot of some of my projects. <br> <br> Below are links to my digital footprint."
        image   = "images/mm_large.png"

    # Call to Action
    [params.cta]
        enable  = true
        title   = "Reach out to me"  
        content = "Like what you see? Connect with me for work, collaborations, new ideas or projects, or just to chat about all things data"  
        btnText = "Email"
        btnURL  = "/contact"

    # Portfolio Section On Homepage
    [params.portfolio]
        enable  = true
        title   = "Projects"
        subtitle= "Browse some of my current data science projects"

    [params.footer]
        [[params.footer.socialIcon]]
            icon = "ion-social-github"
            url = "https://github.com/darwinanddavis"

        [[params.footer.socialIcon]]
            icon = "ion-social-instagram"
            url = "#"

        [[params.footer.socialIcon]]
            icon = "ion-social-linkedin"
            url = "https://www.linkedin.com/in/mmalishev/"

        [[params.footer.socialIcon]]
            icon = "ion-social-twitter"
            url = "https://twitter.com/darwinanddavis"
