baseURL = "https://suspicious-booth-fced28.netlify.com"
languageCode = "en-us"
title = "Matt Malishev"
theme = "timer-hugo"

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

# Site Menus
[menu]
    # Navbar Menus
    [[menu.nav]]
        name    = "About"
        url     = "about"
        weight  = 2
    [[menu.nav]]
        name    = "Blog"
        url     = "blog"
        weight  = 3
    [[menu.nav]]
        name    = "Service"
        url     = "service"
        weight  = 4
    [[menu.nav]]
        name    = "Gallery"
        url     = "gallery"
        weight  = 5
    [[menu.nav]]
        name    = "Contact"
        url     = "contact"
        weight  = 6
    [[menu.nav]]
        name    = "Projects"
        url     = "portfolio"
        weight  = 7

# Site Params
[params]
    home = "Home"
    logo = "images/mm.png"
    dateFormat = "6 January 2006"
    # Meta data
    description = "darwinanddavis"
    author = "Matt Malishev"
    # Google Analitycs
    googleAnalitycsID = "darwinanddavis"

    # Banner Section
    [params.banner]
        enable  = true
        bgImage = "images/mars.jpg"
        heading = "Matt Malishev"
        description = "I like my data diverse, my methods savvy, my analyses reproducible, and my outputs open access."
        btn     = true
        btnText = "Check out my projects"
        btnURL  = "projects"
        [[params.banner.flipText]]
            title   = "spatial modelling"
        [[params.banner.flipText]]
            title   = "simulation modelling"
        [[params.banner.flipText]]
            title   = "geospatial analytics"

    # Homepage About Section
    [params.about]
        enable  = true
        title   = "Bio"
        content = "I’m a computational researcher at Emory University working on diverse data analysis problems from simulation modelling of human disease risk to spatial and bioenergetic modelling of ecological systems. <br> <br> The header tabs provide a snapshot of some of my projects. <br> <br> Below are links to my digital footprint."
        image   = "images/mm_large.png"

    # Call to Action
    [params.cta]
        enable  = true
        title   = "SO WHAT YOU THINK ?"
        content = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nobis,<br>possimus commodi, fugiat magnam temporibus vero magni recusandae? Dolore, maxime praesentium."
        btnText = "Connect with me"
        btnURL  = "/contact"

    # Portfolio Section On Homepage
    [params.portfolio]
        enable  = true
        title   = "Projects"
        subtitle= "Browse some of my current data science projects"

    [params.footer]
        [[params.footer.socialIcon]]
            icon = "ion-social-github"
            url = "https://github.com/darwinanddavis"

        [[params.footer.socialIcon]]
            icon = "ion-social-instagram"
            url = "#"

        [[params.footer.socialIcon]]
            icon = "ion-social-linkedin"
            url = "#"
